size: [300, 600]

variables:
  green:  &green '#47b39d'
  yellow: &yellow '#ffc153'
  orange: &orange '#eb6b56'
  granat: &granat '#b05f6d'
  purple: &purple '#462446'
  graphite: &graphite '#313b48'

style:

  hide-size: true
  hide-address: true
  growth-arrow-size: 2
  stroke-width: 0

areas:
- area:
    style:
        background: *graphite
    title: 'Full Memory Map'
    sections:
      - names: [Text]
        style:
          fill: *green
      - names: [ Initialized data ]
        style:
          fill: *yellow
      - names: [Uninitialized data]
        style:
          fill: *orange
      - names: [ Heap ]
        flags: grows-up
        style:
          fill: *granat
      - names: [ Stack ]
        flags: grows-down
        style:
          fill: *purple
          text-fill: white