size: [1200,1200]

variables:
  graphite: &graphite '#212b38'
  cleargraphite: &cleargraphite '#37465b'
  myturqoise: &myturqoise '#4aefd7'
  mydarkgreen: &mydarkgreen '#08c6ab'
  mypurple: &mypurple '#726eff'

  #mylightblue: &mylightblue '#7bd5f5'
  #myblue: &myblue '#1ca7ec'
  #mydarkblue: &mydarkblue '#1f2f98'
  mylightgrey: &mylightgrey '#F6F6F6'

style:
  text-fill: 'white'
  break-size: 25
  break-type: '≈'
  growth-arrow-size: 2
  growth-arrow-fill: 'white'
  growth-arrow-stroke: 'black'
  background: *graphite
  fill: *mydarkgreen
  hide-size: true
 # stroke: *mydarkblue
  stroke-width: 0
  text-stroke: 'black'
  text-stroke-width: 0.1
  font-size: 12
  font_type: 'Helvetica'

areas:
- area:
    title: STM32F103 Memory Space
    range: [0x0, 0x100000000]
    pos: [ 100, 50 ]
    size: [200, 700]
    style:
      hide-size: true

    sections:
      - names: [none]
        style:
          hide-name: true
          fill: *cleargraphite

- area:
    range: [0x08000000, 0x0801FFFF]
    size: [200, 100]
    pos: [450, 700]
    style:
      hide-size: false
      fill: *myturqoise
    sections:
      - names: [Flash Memory]
        style:
          fill: *mypurple
- area:
    range: [0x1FFFF000, 0x1FFFF80F]
    size: [200, 100]
    pos: [450, 550]
    style:
      hide-size: false
    sections:
      - names: [System Memory]
        style:
          fill: *myturqoise
- area:
    range: [0xE0000000, 0xE1000000]
    size: [200, 200]
    pos: [450, 50]
    style:
      hide-size: false
    sections:
      - names: [ M3 Cortex Internal Peripherals ]

- area:
    title: APB memory space
    range: [0x40000000, 0x40030000]
    pos: [ 750, 50 ]
    size: [ 200, 1000 ]

    sections:
      - names: [Reserved1, Reserved2, Reserved3, Reserved4, Reserved5, Reserved6, Reserved7, Reserved8, Reserved9, Reserved10, Reserved11]
        flags: break
        style:
          fill: *cleargraphite
      - names: [AFIO, EXTI, PORT A, PORT B, PORT C, PORT D, PORT E ]
        style:
          fill: *mypurple


links:
  style:
    opacity: 0.2
    fill: *mylightgrey
    stroke: lightgrey
  sections: [[TIM2, CRC], M3 Cortex Internal Peripherals, Flash Memory, System Memory]


